<?php
$title = 'Liste de ticket';
$this->headTitle($title);
?>
<table class="ui celled padded table">
<tr>
    <th class="single line">Titre</th>
    <th class="single line">Commentaire</th>
</tr>
<?php 
foreach ($tickets->data as $key => $ticket) : ?>
    <tr>
        <?php if(!$ticket->completed): ?>
        <td><?= $this->escapeHtml($ticket->name) ?></td>
        <td><?= $this->escapeHtml($ticket->notes) ?></td>
        <td><button class='ui negative button modal-btn' href='http://zend.local/admin/reply/<?= $ticket->id ?>'>Répondre</button></td>
        <?php endif; ?>
    </tr>
<?php endforeach; ?>
</table>
<?php
var_dump($tickets);
var_dump($tickets->data);
?>