<?php
$title = 'Liste de ticket';
$this->headTitle($title);
?>
<div class="ui center aligned container">
    <h1 class="ui blue header">Liste des tickets</h1>
</div>
<table class="ui compact celled definition table">
    <thead>
        <tr>
            <th></th>
            <th><h2>Titre</h2></th>
            <th colspan="2"><h2>Commentaire</h2></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($tickets->data as $key => $ticket) : ?>
            <tr>
                <?php if ($ticket->completed == false && $ticket->memberships[0]->section == null): ?>
                    <td class="collapsing">
                        <div class="ui toggle ticket_toggle checkbox">
                            <input type="checkbox" value="<?= $ticket->id ?>"><label></label>
                        </div>
                    </td>
                    <td><?= $this->escapeHtml($ticket->name) ?></td>
                    <td><?= $this->escapeHtml($ticket->notes) ?></td>
                    <td class="right aligned"><a class='ui negative button modal-btn' href='http://zend.local/admin/reply/<?= $ticket->id ?>'>Répondre</a></td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<a class='ui blue button modal-btn' href="/admin/reply">Répondre</a>

<script>
    $(document).ready(function () {

        var btn = $('.blue.button.modal-btn');

        var toggles = $('.ticket_toggle');
        toggles.checkbox({
            onChange: function() {
                var selected = [];
                toggles.map(function () {
                    if ($(this).checkbox('is checked')) {
                        selected.push($(this).find('input').val());
                    }
                });

                btn.data("data", {"selected": selected} );
            }
        });
    });
</script>
