<div class="ui middle aligned center aligned grid">
    <div class="column">
        <h2 class="ui teal image header">Connexion à votre compte</h2>
        <form class="ui large form">
            <div class="ui stacked segment">
                <div class="field">
                    <div class="ui left icon input">
                        <i class="user icon"></i>
                        <input type="text" name="email" placeholder="Adresse E-mail">
                    </div>
                </div>
                <div class="field">
                    <div class="ui left icon input">
                        <i class="lock icon"></i>
                        <input type="password" name="password" placeholder="Mot de passe">
                    </div>
                </div>
                <div class="ui fluid large teal submit button">Connexion</div>
            </div>
            <div class="ui error message"></div>
        </form>
    </div>
</div>