<div class="ui modal">
    <div class="header">
        <h1>Tâche principal :</h1>
    </div>
    <div class="content">
        <div class="field">
            <?php
            echo '<h3>' . $main_ticket->name . ' : </h3></br>';
            echo $main_ticket->notes . '</br>';
            ?>
            <table class="ui celled striped table">
                <thead>
                    <tr><th colspan="2">
                            <h3>Tâche(s)</h3>
                        </th>
                        <th>Mail</th>
                    </tr></thead>
                <tbody>

                    <?php foreach ($tickets as $ticket) : ?>
                        <tr>
                            <td class="collapsing"><?= $ticket->name ?></td>
                            <td><?= $ticket->notes ?></td>
                            <td>
                                <?php
                                $mail_field = array_filter($ticket->custom_fields, function($field) {
                                    return ($field->name == "email" && !empty($field->text_value));
                                });

                                if (!empty($mail_field)) {
                                    echo $mail_field[0]->text_value;
                                }
                                ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <?php
            var_dump($tickets);
            ?>
        </div>
        <p>Réponse : </p>
        <div class="ui form">
            <div class="field">
                <textarea></textarea>
                <div class="two wide column">
                    <button class="ui fluid button" type="submit" name="Repondre">Envoyer votre réponse</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('document').ready(function () {
        $('.ui.modal').modal('show');
    });
</script>
