
<form class="ui form" method="post" action="http://zend.local/send-email">
    <div class="ui modal">
        <div class="content">
            <table class="ui celled striped table">
                <thead>
                    <tr><th colspan="2">
                            <h3>Tâche(s)</h3>
                        </th>
                        <th>Mail</th>
                    </tr></thead>
                <tbody>

                    <?php foreach ($tickets as $ticket) : ?>
                        <tr>
                            <td class="collapsing"><?= $ticket->name ?></td>
                            <td><?= $ticket->notes ?></td>
                            <td>
                                <?php
                                $mail_field = array_filter($ticket->custom_fields, function($field) {
                                    return ($field->name == "email" && !empty($field->text_value));
                                });

                                if (!empty($mail_field)) {
                                    $mail = $mail_field[0]->text_value;
                                    echo $mail;
                                    echo '<input type="hidden" name="emails[]" value="'.$mail.'">';
                                }
                                ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <br>
            <h1>Réponse : </h1>
            <div class="field">
                <textarea name="reply"></textarea>
            </div>
        </div>
        <div class="actions">
            <div class="ui positive right labeled icon button">
                Valider
                <i class="checkmark icon"></i>
            </div>

        </div>

    </div>
</form>


<?php
var_dump($tickets);
?>

<script type="text/javascript">
    $('document').ready(function () {
        
        var form_settings = {
            on: 'submit',
            inline: true,
            fields: {
                reply: 'empty'
            },
            onSuccess: function (event, values) {
                var url = $('.ui.form').attr('action');
                
                $.post(url, values, function(data) {
                    
                    console.log(data);
                });
                
            },
            onFailure: function () {
                console.log("fail");
            }
        }

        $('.ui.form').form(form_settings);

        $('.ui.modal').modal({
            onApprove: function () {
                $('.ui.form').form('validate form');
                return false;
            }
        });
        $('.ui.modal').modal('show');
    });

</script>
