<div class="ui modal">
    <div class="header">
        <h1>Tâche principal :</h1>
    </div>
    <div class="content">
        <div class="field">
            <?php
            echo '<h3>' . $ticket->name . ' : </h3></br>';
            echo $ticket->notes . '</br>';
            ?>
            <table class="ui celled striped table">
                <thead>
                    <tr><th colspan="2">
                            <h3>Sous-Tâche(s)</h3>
                        </th>
                    </tr></thead>
                <tbody>

                    <?php foreach ($subtasks->data as $subtask) : ?>

                        <tr><td class="collapsing"><?= $subtask->name ?></td>
                            <td><?= $subtask->notes ?></td></tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <?php
            var_dump($subtasks);
            ?>
        </div>
        <p>Réponse : </p>
        <div class="ui form">
            <div class="field">
                <textarea></textarea>
                <div class="two wide column">
                    <button class="ui fluid button" type="submit" name="Repondre">Envoyer votre réponse</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('document').ready(function () {
        $('.ui.modal').modal('show');
    });
</script>
