<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <link type="text/css" id="dark-mode" rel="stylesheet">
        <style type="text/css" id="dark-mode-custom-style"></style>
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('semantic/dist/semantic.min.css'))
        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('semantic/dist/semantic.min.js'))
                ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <div class="ui inverted menu">
            <div class="ui container">
                <div class="header item">Gestionnaire de tickets</div>
                <a class="item  " href="http://zend.local/">Accueil</a>
                <a class="item" href="http://zend.local/user">Nouveau Ticket</a>
                <a class="item" href="http://zend.local/admin">Liste des Tickets</a>
                <div class="right menu">
                    <a class="item" href="http://zend.local/login">Connexion</a>
                </div>
            </div>
        </div>
        <div class="ui text container">
            <?= $this->content ?>
        </div>
        <div class="ui container">
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div>

        <div id="modal"></div>
        <?= $this->inlineScript() ?>

    </body>
</html>

<script type="text/javascript">
    $(document).ready(function () {

        var loading = false;

        $('.modal-btn').click(function (e) {

            if (loading === true) {
                return;
            }
            loading = true;

            var btn = $(this);
            
            $.post(btn.attr("href"), btn.data("data"), function (content) {
                $(".modals.page").remove();
                $('#modal').html(content);

                loading = false;
            });

            e.preventDefault();
        });

    });
</script>
